programa5_1: Ejercicio3.cpp PoligonoIrreg.o
	g++ Ejercicio3.cpp PoligonoIrreg.o Coordenada.o -o 3
PoligonoIrreg.o: PoligonoIrreg.cpp Coordenada.o PoligonoIrreg.h
	g++ PoligonoIrreg.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c
