
import java.io.File;
import java.net.DatagramPacket;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author agust
 */
public class cliente_menu extends javax.swing.JFrame {

    public static DefaultListModel modelo;
    /**
     * Creates new form cliente_menu
     */
    public cliente_menu() {
        initComponents();
        jEditorPane1.setContentType("text/html");
        jEditorPane1.setEditable(false);
        jEditorPane1.setText("");
        modelo = new DefaultListModel();
        jList1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Servidores Disponibles");

        jButton1.setText("Actualizar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Ingrese el nombre del archivo");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Nodo anterior");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Nodo actual");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Nodo siguiente");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Progreso");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Notificaciones");

        jScrollPane4.setViewportView(jTextPane1);

        jScrollPane5.setViewportView(jTextPane2);

        jScrollPane6.setViewportView(jTextPane3);

        jButton3.setText("Descargar archivo");

        jScrollPane2.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DatagramPacket p1;
        DatagramPacket p;
        InetAddress gpo = null;
        try{
            MulticastSocket s = new MulticastSocket(4000);
            s.setReuseAddress(true);
            s.setTimeToLive(1);
            String destinatario = modelo.get(0).toString();
            String archivo = jTextField1.getText();
            String msj = destinatario;
            System.out.println(msj);
            String global = "Inicio";
            byte[] b = msj.getBytes();
            System.out.println("tamaño del mansaje: "+b.length);
            byte[] b1 = global.getBytes();
            gpo = InetAddress.getByName("228.1.1.1");
            s.joinGroup(gpo);                           //Se une al grupo
            p1 = new DatagramPacket(b1, b1.length, gpo, 4000);
            p = new DatagramPacket(b, b.length, gpo, 4000); // se recibbe el paquete en puerto 9999            
            s.send(p1);
            s.send(p);  
            jTextField1.setText("");
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cliente_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cliente_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cliente_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cliente_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new cliente_menu().setVisible(true);
        String cadena = "";
        String respuesta = "";
        String privado = "";
        String archivo = "";
        InetAddress gpo = null;
        DatagramPacket identificador;
        DatagramPacket p;
        DatagramPacket p1;
        DatagramPacket p2;
        ArrayList<String> servidores = new ArrayList();
        int pos = 0;
        //int cantidad = 2;
        String aux2 = new String();
        try{
            MulticastSocket cl = new MulticastSocket(4000); //se envia el paquete en el puerto 9876
            cl.setReuseAddress(true);
            try {
                gpo = InetAddress.getByName("228.1.1.1");
            } catch (UnknownHostException e) {
                JOptionPane.showMessageDialog(null, "Direccion no válida");
            }
            cl.joinGroup(gpo);
            String cliente = "Cliente";
            byte[] inicio = cliente.getBytes();
            identificador = new DatagramPacket(inicio, inicio.length, gpo, 4000);
            cl.send(identificador);
            
            for(;;){
                p = new DatagramPacket(new byte[2048], 2048);
                cl.receive(p);
                String msj = new String(p.getData());
                System.out.println("Mensaje recibido: "+msj);

                if (msj.contains("Mensaje para Cliente")) {
                    System.out.println("Entramos un mensaje privado");
                    if(msj.contains("no existe")){
                        
                    }
                    else{
                        
                    }
                } 
                
                else if(msj.contains("Inicio")){
                    System.out.println("Inicio de la busqueda");
                    jEditorPane1.setText("Cliente --> Solicito archivo");
                    jTextPane1.removeAll();
                    jTextPane1.setText("No hay anterior");
                    jTextPane2.removeAll();
                    if(modelo.size() > 1){
                        String siguiente = (String)modelo.getElementAt(1);
                        jTextPane2.setText(siguiente);
                    }
                    else{
                        jTextPane2.setText("No hay siguiente");
                   }
                    jTextPane3.removeAll();
                    String actual = (String)modelo.getElementAt(0);
                    jTextPane3.setText(actual);
                }
                
                else if (msj.contains("Anterior")) {
                    System.out.println("Archivo encontrado");
                    if(pos != 0){
                        String posicion = (String)modelo.getElementAt(pos);
                        jEditorPane1.setText(posicion+"---->Archivo Encontrado");
                        jTextPane1.removeAll();
                        String anterior = (String)modelo.getElementAt(pos-1);
                        jTextPane1.setText(anterior);
                        if(pos+1 >= modelo.size()-1){
                            jTextPane2.removeAll();
                            jTextPane2.setText("No hay siguiente");
                        }
                        else{
                            jTextPane2.removeAll();
                            String siguiente = (String)modelo.getElementAt(pos+1);
                            jTextPane2.setText(siguiente);
                        }
                        jTextPane3.removeAll();
                        String actual = (String)modelo.getElementAt(pos);
                        jTextPane3.setText(actual);
                        pos--;
                    }
                    else{
                        String posicion = (String)modelo.getElementAt(pos);
                        jEditorPane1.setText(posicion+"---->Archivo Encontrado");
                        jTextPane1.removeAll();
                        jTextPane1.setText("No hay anterior");
                        if(pos+1 >= modelo.size()-1){
                            jTextPane2.removeAll();
                            jTextPane2.setText("No hay siguiente");
                        }
                        else{
                            jTextPane2.removeAll();
                            String siguiente = (String)modelo.getElementAt(pos+1);
                            jTextPane2.setText(siguiente);
                        }
                        jTextPane3.removeAll();
                        String actual = (String)modelo.getElementAt(pos);
                        jTextPane3.setText(actual);
                    }
                } 
                
                else if (msj.contains("Siguiente")) {
                    System.out.println("Archivo no encontrado");
                    if(pos < modelo.getSize()-1){
                        String posicion = (String)modelo.getElementAt(pos);
                        jEditorPane1.setText(posicion+"---->Archivo no encontrado");
                        if(pos == 0){
                            jTextPane1.removeAll();
                            jTextPane1.setText("No hay anterior");
                            if(pos+1 >= modelo.size()-1){
                                jTextPane2.removeAll();
                                jTextPane2.setText("No hay siguiente");
                            }
                            else{
                                jTextPane2.removeAll();
                                String siguiente = (String)modelo.getElementAt(pos+1);
                                jTextPane2.setText(siguiente);
                            }
                            jTextPane3.removeAll();
                            String actual = (String)modelo.getElementAt(pos);
                            jTextPane3.setText(actual);
                            pos++;
                        }
                        else{
                            jTextPane1.removeAll();
                            String anterior = (String)modelo.getElementAt(pos-1);
                            jTextPane1.setText(anterior);
                            if(pos+1 >= modelo.size()-1){
                                jTextPane2.removeAll();
                                jTextPane2.setText("No hay siguiente");
                            }
                            else{
                                jTextPane2.removeAll();
                                String siguiente = (String)modelo.getElementAt(pos+1);
                                jTextPane2.setText(siguiente);
                            }
                            jTextPane3.removeAll();
                            String actual = (String)modelo.getElementAt(pos);
                            jTextPane3.setText(actual);
                            pos++; 
                        }
                    }
                    else{
                        String posicion = (String)modelo.getElementAt(pos);
                        jEditorPane1.setText(posicion+"---->Archivo no encontrado");
                        if(pos == 0){
                            jTextPane1.removeAll();
                            jTextPane1.setText("No hay anterior");
                            jTextPane2.removeAll();
                            jTextPane2.setText("No hay siguiente");
                            jTextPane3.removeAll();
                            String actual = (String)modelo.getElementAt(pos);
                            jTextPane3.setText(actual);
                        }
                        else{
                            jTextPane1.removeAll();
                            String anterior = (String)modelo.getElementAt(pos-1);
                            jTextPane1.setText(anterior);
                            jTextPane2.removeAll();
                            jTextPane2.setText("No hay siguiente");
                            jTextPane3.removeAll();
                            String actual = (String)modelo.getElementAt(pos);
                            jTextPane3.setText(actual);
                        }
                    }
                } 
                
                else if (msj.contains("Cliente                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ")) {
                    System.out.println("Se conecto el cliente");
                } 
                
                else if(msj.contains("Mensaje")){
                    System.out.println("Es privado");
                }
                
                else {
                    System.out.println("Recibi un nombre");
                    aux2 += msj;
                    Pattern regex = Pattern.compile("\\b" + Pattern.quote(msj) + "\\b", Pattern.CASE_INSENSITIVE);
                    Matcher match = regex.matcher(aux2);
                    if (!match.find()) {
                        modelo.addElement(msj);
                    }
                }
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public static javax.swing.JEditorPane jEditorPane1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JList<String> jList1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTextField jTextField1;
    public static javax.swing.JTextPane jTextPane1;
    public static javax.swing.JTextPane jTextPane2;
    public static javax.swing.JTextPane jTextPane3;
/*
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
*/}
