package com.Calculadora.LogicaDeNegocios;

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 18 21:00:50 CDT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TKN_E = 28;
  public static final int TKN_COSH = 17;
  public static final int TKN_PCIERRA = 30;
  public static final int TKN_COS = 14;
  public static final int TKN_TANH = 18;
  public static final int TKN_NUMREAL = 2;
  public static final int TKN_SENH = 16;
  public static final int TKN_ERROR = 31;
  public static final int TKN_MULT = 9;
  public static final int TKN_PTOCOMA = 6;
  public static final int TKN_POT = 12;
  public static final int TKN_PI = 27;
  public static final int TKN_EXP = 26;
  public static final int TKN_LOG = 22;
  public static final int UMENOS = 32;
  public static final int TKN_ARCSEN = 19;
  public static final int TKN_VARZ = 5;
  public static final int TKN_VARY = 4;
  public static final int TKN_VARX = 3;
  public static final int TKN_DEG = 25;
  public static final int TKN_ARCTAN = 21;
  public static final int TKN_DIV = 10;
  public static final int EOF = 0;
  public static final int UMAS = 33;
  public static final int TKN_SEN = 13;
  public static final int error = 1;
  public static final int TKN_ARCCOS = 20;
  public static final int TKN_TAN = 15;
  public static final int TKN_MAS = 7;
  public static final int TKN_PABRE = 29;
  public static final int TKN_SQRT = 23;
  public static final int TKN_RAD = 24;
  public static final int TKN_MOD = 11;
  public static final int TKN_MENOS = 8;
}

