/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.Calculadora;

import com.Calculadora.LogicaDeNegocios.Modulo_LogicaDeNegocios;

/**
 *
 * @author Checo
 */
public class JFrame_CalculadoraCasio_fx82MS extends javax.swing.JFrame {

    ///Atributos
    private String modoTrigonometrica="NORMAL";
    private double varX=0.0;
    private double varY=0.0;
    private double varZ=0.0;
    
    /**
     * Creates new form JFrame_CalculadoraCasio_fx82MS
     */
    public JFrame_CalculadoraCasio_fx82MS() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_TITULO = new javax.swing.JLabel();
        jTextField_Display = new javax.swing.JTextField();
        jButton_LOG = new javax.swing.JButton();
        jButton_SQRT = new javax.swing.JButton();
        jButton_EXP = new javax.swing.JButton();
        jButton_SEN = new javax.swing.JButton();
        jButton_COS = new javax.swing.JButton();
        jButton_TAN = new javax.swing.JButton();
        jButton_HYP = new javax.swing.JButton();
        jButton_PABRE = new javax.swing.JButton();
        jButton_PCIERRA = new javax.swing.JButton();
        jButton_POT = new javax.swing.JButton();
        jButton_RAD = new javax.swing.JButton();
        jButton_DEG = new javax.swing.JButton();
        jButton_ARC = new javax.swing.JButton();
        jButton_E = new javax.swing.JButton();
        jButton_PI = new javax.swing.JButton();
        jButton_MOD = new javax.swing.JButton();
        jButton_DEL = new javax.swing.JButton();
        jButton_AC = new javax.swing.JButton();
        jButton_POR = new javax.swing.JButton();
        jButton_ENTRE = new javax.swing.JButton();
        jButton_MAS = new javax.swing.JButton();
        jButton_MENOS = new javax.swing.JButton();
        jButton_IGUAL = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jButton_PUNTO = new javax.swing.JButton();
        jTextField_varX = new javax.swing.JTextField();
        jTextField_varY = new javax.swing.JTextField();
        jTextField_varZ = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_varX = new javax.swing.JButton();
        jButton_varY = new javax.swing.JButton();
        jButton_varZ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAEAAV EVALUADOR");
        setBackground(new java.awt.Color(0, 51, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jLabel_TITULO.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_TITULO.setText("Evaluador de Expresiones SAEAAV");

        jTextField_Display.setBackground(new java.awt.Color(153, 255, 204));
        jTextField_Display.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton_LOG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_LOG.setText("LOG");
        jButton_LOG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_LOGMouseClicked(evt);
            }
        });

        jButton_SQRT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_SQRT.setText("SQRT");
        jButton_SQRT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SQRTMouseClicked(evt);
            }
        });

        jButton_EXP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_EXP.setText("EXP");
        jButton_EXP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_EXPMouseClicked(evt);
            }
        });

        jButton_SEN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_SEN.setText("SEN");
        jButton_SEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SENMouseClicked(evt);
            }
        });

        jButton_COS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_COS.setText("COS");
        jButton_COS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_COSMouseClicked(evt);
            }
        });

        jButton_TAN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_TAN.setText("TAN");
        jButton_TAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_TANMouseClicked(evt);
            }
        });

        jButton_HYP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_HYP.setText("HYP");
        jButton_HYP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_HYPMouseClicked(evt);
            }
        });

        jButton_PABRE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_PABRE.setText("(");
        jButton_PABRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PABREMouseClicked(evt);
            }
        });

        jButton_PCIERRA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_PCIERRA.setText(")");
        jButton_PCIERRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PCIERRAMouseClicked(evt);
            }
        });

        jButton_POT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_POT.setText("^");
        jButton_POT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_POTMouseClicked(evt);
            }
        });

        jButton_RAD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_RAD.setText("RAD");
        jButton_RAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_RADMouseClicked(evt);
            }
        });

        jButton_DEG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_DEG.setText("DEG");
        jButton_DEG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_DEGMouseClicked(evt);
            }
        });

        jButton_ARC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_ARC.setText("ARC");
        jButton_ARC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ARCMouseClicked(evt);
            }
        });

        jButton_E.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_E.setText("E");
        jButton_E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_EMouseClicked(evt);
            }
        });

        jButton_PI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_PI.setText("PI");
        jButton_PI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PIMouseClicked(evt);
            }
        });

        jButton_MOD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_MOD.setText("MOD");
        jButton_MOD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_MODMouseClicked(evt);
            }
        });

        jButton_DEL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_DEL.setText("SALIR");
        jButton_DEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_DELMouseClicked(evt);
            }
        });

        jButton_AC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_AC.setText("CLR");
        jButton_AC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ACMouseClicked(evt);
            }
        });

        jButton_POR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_POR.setText("X");
        jButton_POR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PORMouseClicked(evt);
            }
        });

        jButton_ENTRE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_ENTRE.setText("/");
        jButton_ENTRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ENTREMouseClicked(evt);
            }
        });

        jButton_MAS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_MAS.setText("+");
        jButton_MAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_MASMouseClicked(evt);
            }
        });

        jButton_MENOS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_MENOS.setText("-");
        jButton_MENOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_MENOSMouseClicked(evt);
            }
        });

        jButton_IGUAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_IGUAL.setText("=");
        jButton_IGUAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_IGUALMouseClicked(evt);
            }
        });

        jButton_7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_7.setText("7");
        jButton_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_7MouseClicked(evt);
            }
        });

        jButton_8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_8.setText("8");
        jButton_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_8MouseClicked(evt);
            }
        });

        jButton_9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_9.setText("9");
        jButton_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_9MouseClicked(evt);
            }
        });

        jButton_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_4.setText("4");
        jButton_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_4MouseClicked(evt);
            }
        });

        jButton_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_5.setText("5");
        jButton_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_5MouseClicked(evt);
            }
        });

        jButton_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_6.setText("6");
        jButton_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_6MouseClicked(evt);
            }
        });

        jButton_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_1.setText("1");
        jButton_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_1MouseClicked(evt);
            }
        });

        jButton_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_2.setText("2");
        jButton_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_2MouseClicked(evt);
            }
        });

        jButton_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_3.setText("3");
        jButton_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_3MouseClicked(evt);
            }
        });

        jButton_0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_0.setText("0");
        jButton_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_0MouseClicked(evt);
            }
        });

        jButton_PUNTO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_PUNTO.setText(".");
        jButton_PUNTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PUNTOMouseClicked(evt);
            }
        });

        jTextField_varX.setText("0.0");

        jTextField_varY.setText("0.0");

        jTextField_varZ.setText("0.0");

        jLabel1.setText("X=");

        jLabel2.setText("Y=");

        jLabel3.setText("Z=");

        jButton_varX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_varX.setForeground(new java.awt.Color(204, 0, 0));
        jButton_varX.setText("X");
        jButton_varX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_varXMouseClicked(evt);
            }
        });

        jButton_varY.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_varY.setForeground(new java.awt.Color(204, 0, 0));
        jButton_varY.setText("Y");
        jButton_varY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_varYMouseClicked(evt);
            }
        });

        jButton_varZ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_varZ.setForeground(new java.awt.Color(204, 0, 0));
        jButton_varZ.setText("Z");
        jButton_varZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_varZMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_Display, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_LOG)
                                    .addComponent(jButton_RAD)
                                    .addComponent(jButton_DEL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_varY, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_varX, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_varZ, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_SQRT)
                            .addComponent(jButton_DEG)
                            .addComponent(jButton_MOD)
                            .addComponent(jButton_7)
                            .addComponent(jButton_4)
                            .addComponent(jButton_1)
                            .addComponent(jButton_0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_EXP)
                            .addComponent(jButton_HYP)
                            .addComponent(jButton_ARC)
                            .addComponent(jButton_8)
                            .addComponent(jButton_5)
                            .addComponent(jButton_2)
                            .addComponent(jButton_PUNTO))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_IGUAL)
                            .addComponent(jButton_3)
                            .addComponent(jButton_SEN)
                            .addComponent(jButton_POT)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton_9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_E, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jButton_6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_PI)
                                    .addComponent(jButton_COS)
                                    .addComponent(jButton_PABRE)
                                    .addComponent(jButton_MAS)
                                    .addComponent(jButton_POR))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jButton_ENTRE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jButton_PCIERRA))
                                    .addComponent(jButton_TAN)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton_AC))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton_varY)
                                            .addComponent(jButton_MENOS)))))
                            .addComponent(jButton_varX)
                            .addComponent(jButton_varZ))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_TITULO)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_TITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_LOG)
                    .addComponent(jButton_SQRT)
                    .addComponent(jButton_EXP)
                    .addComponent(jButton_PABRE)
                    .addComponent(jButton_PCIERRA)
                    .addComponent(jButton_POT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_SEN)
                    .addComponent(jButton_COS)
                    .addComponent(jButton_TAN)
                    .addComponent(jButton_HYP)
                    .addComponent(jButton_RAD)
                    .addComponent(jButton_DEG))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ARC)
                    .addComponent(jButton_E)
                    .addComponent(jButton_PI)
                    .addComponent(jButton_MOD)
                    .addComponent(jButton_DEL)
                    .addComponent(jButton_AC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_POR)
                    .addComponent(jButton_ENTRE)
                    .addComponent(jButton_7)
                    .addComponent(jButton_8)
                    .addComponent(jButton_9)
                    .addComponent(jTextField_varX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_MAS)
                    .addComponent(jButton_MENOS)
                    .addComponent(jButton_4)
                    .addComponent(jButton_5)
                    .addComponent(jButton_6)
                    .addComponent(jTextField_varY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_1)
                    .addComponent(jButton_2)
                    .addComponent(jButton_3)
                    .addComponent(jTextField_varZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton_varX)
                    .addComponent(jButton_varY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_0)
                    .addComponent(jButton_PUNTO)
                    .addComponent(jButton_IGUAL)
                    .addComponent(jButton_varZ))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LOGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LOGMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"LOG(");
    }//GEN-LAST:event_jButton_LOGMouseClicked

    private void jButton_SQRTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SQRTMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"SQRT(");
    }//GEN-LAST:event_jButton_SQRTMouseClicked

    private void jButton_EXPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EXPMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"EXP(");
    }//GEN-LAST:event_jButton_EXPMouseClicked

    private void jButton_POTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_POTMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"^");
    }//GEN-LAST:event_jButton_POTMouseClicked

    private void jButton_PABREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PABREMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"(");
    }//GEN-LAST:event_jButton_PABREMouseClicked

    private void jButton_PCIERRAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PCIERRAMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+")");
    }//GEN-LAST:event_jButton_PCIERRAMouseClicked

    private void jButton_RADMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RADMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"RAD(");
    }//GEN-LAST:event_jButton_RADMouseClicked

    private void jButton_DEGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DEGMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"DEG(");
    }//GEN-LAST:event_jButton_DEGMouseClicked

    private void jButton_MODMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_MODMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"%");
    }//GEN-LAST:event_jButton_MODMouseClicked

    private void jButton_EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"E");
    }//GEN-LAST:event_jButton_EMouseClicked

    private void jButton_PIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PIMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"PI");
    }//GEN-LAST:event_jButton_PIMouseClicked

    private void jButton_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_7MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"7");
    }//GEN-LAST:event_jButton_7MouseClicked

    private void jButton_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_8MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"8");
    }//GEN-LAST:event_jButton_8MouseClicked

    private void jButton_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_9MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"9");
    }//GEN-LAST:event_jButton_9MouseClicked

    private void jButton_PORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PORMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"*");
    }//GEN-LAST:event_jButton_PORMouseClicked

    private void jButton_ENTREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ENTREMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"/");
    }//GEN-LAST:event_jButton_ENTREMouseClicked

    private void jButton_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_4MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"4");
    }//GEN-LAST:event_jButton_4MouseClicked

    private void jButton_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_5MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"5");
    }//GEN-LAST:event_jButton_5MouseClicked

    private void jButton_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_6MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"6");
    }//GEN-LAST:event_jButton_6MouseClicked

    private void jButton_MASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_MASMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"+");
    }//GEN-LAST:event_jButton_MASMouseClicked

    private void jButton_MENOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_MENOSMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"-");
    }//GEN-LAST:event_jButton_MENOSMouseClicked

    private void jButton_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_1MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"1");
    }//GEN-LAST:event_jButton_1MouseClicked

    private void jButton_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_2MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"2");
    }//GEN-LAST:event_jButton_2MouseClicked

    private void jButton_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_3MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"3");
    }//GEN-LAST:event_jButton_3MouseClicked

    private void jButton_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_0MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"0");
    }//GEN-LAST:event_jButton_0MouseClicked

    private void jButton_PUNTOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PUNTOMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+".");
    }//GEN-LAST:event_jButton_PUNTOMouseClicked

    private void jButton_IGUALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_IGUALMouseClicked
        //AQUI RESUELVE
        //PROCESAMOS DIRECTO
        
        //Variables
        String contenido;
        String texto;
        
        //Leemos los datos del campo
        String textoDisplay=this.jTextField_Display.getText();
        contenido=textoDisplay+";";
        
        //Ahora los procesamos
        Modulo_LogicaDeNegocios objModulo_LogicaDeNegocios=new Modulo_LogicaDeNegocios();
        
        //Ajustamos
        texto= this.jTextField_varX.getText();
        this.varX=Double.parseDouble(texto);
        texto= this.jTextField_varY.getText();
        this.varY=Double.parseDouble(texto);
        texto= this.jTextField_varZ.getText();
        this.varZ=Double.parseDouble(texto);
        
        //Procesamos
        objModulo_LogicaDeNegocios.procesarContenido_ContemplarUsoDeVariablesXYZ(contenido, this.varX, this.varY, this.varZ);
        
        //Obtenemos resultados
        contenido=objModulo_LogicaDeNegocios.obtenerResultadosYaProcesados();
        
        //Le damos salida
        this.jTextField_Display.setText(contenido);
    }//GEN-LAST:event_jButton_IGUALMouseClicked

    private void jButton_HYPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_HYPMouseClicked
       this.modoTrigonometrica="HYP";
    }//GEN-LAST:event_jButton_HYPMouseClicked

    private void jButton_ARCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ARCMouseClicked
       this.modoTrigonometrica="ARC";
    }//GEN-LAST:event_jButton_ARCMouseClicked

    private void jButton_SENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SENMouseClicked
       String textoDisplay=this.jTextField_Display.getText();
       switch(this.modoTrigonometrica)
       {
           case "HYP":
               this.jTextField_Display.setText(textoDisplay+"SENH(");
           break;
           case "ARC":
               this.jTextField_Display.setText(textoDisplay+"ARCSEN(");
           break;
           case "NORMAL":
               this.jTextField_Display.setText(textoDisplay+"SEN(");
           break;
       }
       this.modoTrigonometrica="NORMAL";
    }//GEN-LAST:event_jButton_SENMouseClicked

    private void jButton_COSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_COSMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
       switch(this.modoTrigonometrica)
       {
           case "HYP":
               this.jTextField_Display.setText(textoDisplay+"COSH(");
           break;
           case "ARC":
               this.jTextField_Display.setText(textoDisplay+"ARCCOS(");
           break;
           case "NORMAL":
               this.jTextField_Display.setText(textoDisplay+"COS(");
           break;
       }
       this.modoTrigonometrica="NORMAL";
    }//GEN-LAST:event_jButton_COSMouseClicked

    private void jButton_TANMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_TANMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
       switch(this.modoTrigonometrica)
       {
           case "HYP":
               this.jTextField_Display.setText(textoDisplay+"TANH(");
           break;
           case "ARC":
               this.jTextField_Display.setText(textoDisplay+"ARCTAN(");
           break;
           case "NORMAL":
               this.jTextField_Display.setText(textoDisplay+"TAN(");
           break;
       }
       this.modoTrigonometrica="NORMAL";
    }//GEN-LAST:event_jButton_TANMouseClicked

    private void jButton_ACMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ACMouseClicked
        this.jTextField_Display.setText("");
    }//GEN-LAST:event_jButton_ACMouseClicked

    private void jButton_DELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DELMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton_DELMouseClicked

    private void jButton_varXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_varXMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"X");
    }//GEN-LAST:event_jButton_varXMouseClicked

    private void jButton_varYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_varYMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"Y");
    }//GEN-LAST:event_jButton_varYMouseClicked

    private void jButton_varZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_varZMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"Z");
    }//GEN-LAST:event_jButton_varZMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_CalculadoraCasio_fx82MS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_CalculadoraCasio_fx82MS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_CalculadoraCasio_fx82MS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_CalculadoraCasio_fx82MS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_CalculadoraCasio_fx82MS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JButton jButton_AC;
    private javax.swing.JButton jButton_ARC;
    private javax.swing.JButton jButton_COS;
    private javax.swing.JButton jButton_DEG;
    private javax.swing.JButton jButton_DEL;
    private javax.swing.JButton jButton_E;
    private javax.swing.JButton jButton_ENTRE;
    private javax.swing.JButton jButton_EXP;
    private javax.swing.JButton jButton_HYP;
    private javax.swing.JButton jButton_IGUAL;
    private javax.swing.JButton jButton_LOG;
    private javax.swing.JButton jButton_MAS;
    private javax.swing.JButton jButton_MENOS;
    private javax.swing.JButton jButton_MOD;
    private javax.swing.JButton jButton_PABRE;
    private javax.swing.JButton jButton_PCIERRA;
    private javax.swing.JButton jButton_PI;
    private javax.swing.JButton jButton_POR;
    private javax.swing.JButton jButton_POT;
    private javax.swing.JButton jButton_PUNTO;
    private javax.swing.JButton jButton_RAD;
    private javax.swing.JButton jButton_SEN;
    private javax.swing.JButton jButton_SQRT;
    private javax.swing.JButton jButton_TAN;
    private javax.swing.JButton jButton_varX;
    private javax.swing.JButton jButton_varY;
    private javax.swing.JButton jButton_varZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_TITULO;
    private javax.swing.JTextField jTextField_Display;
    private javax.swing.JTextField jTextField_varX;
    private javax.swing.JTextField jTextField_varY;
    private javax.swing.JTextField jTextField_varZ;
    // End of variables declaration//GEN-END:variables
}
