/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.SAEAAV.Vista;

/**
 *
 * @author Checo
 */
public class UTL_Esclavo_JPanel_CalculadoraCasio_fx82MS extends javax.swing.JPanel {

    ///Atributos
    private String modoTrigonometrica="NORMAL";
    private double varX=0.0;
    private double varY=0.0;
    private double varZ=0.0;
    private String expresionDelUsuario="";
    private boolean trabajando=false;
    private javax.swing.JTextField jTextField_campoTextoExpresion=null;
    private javax.swing.JFrame jFrame_VentanaInvoca=null;
    
    /**
     * Creates new form UTL_Esclavo_JPanel_CalculadoraCasio_fx82MS
     */
    public UTL_Esclavo_JPanel_CalculadoraCasio_fx82MS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_TITULO = new javax.swing.JLabel();
        jButton_RAD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_varX = new javax.swing.JButton();
        jButton_varY = new javax.swing.JButton();
        jButton_varZ = new javax.swing.JButton();
        jButton_DEL = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_PUNTO = new javax.swing.JButton();
        jButton_IGUAL = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_E = new javax.swing.JButton();
        jButton_PI = new javax.swing.JButton();
        jButton_POR = new javax.swing.JButton();
        jButton_MAS = new javax.swing.JButton();
        jButton_MENOS = new javax.swing.JButton();
        jButton_ENTRE = new javax.swing.JButton();
        jButton_AC = new javax.swing.JButton();
        jButton_TAN = new javax.swing.JButton();
        jButton_PCIERRA = new javax.swing.JButton();
        jButton_Borrar = new javax.swing.JButton();
        jTextField_Display = new javax.swing.JTextField();
        jButton_PABRE = new javax.swing.JButton();
        jButton_COS = new javax.swing.JButton();
        jButton_SEN = new javax.swing.JButton();
        jButton_POT = new javax.swing.JButton();
        jButton_EXP = new javax.swing.JButton();
        jButton_HYP = new javax.swing.JButton();
        jButton_ARC = new javax.swing.JButton();
        jButton_MOD = new javax.swing.JButton();
        jButton_DEG = new javax.swing.JButton();
        jButton_SQRT = new javax.swing.JButton();
        jButton_LOG = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_TITULO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_TITULO.setText("Evaluador de Expresiones SAEAAV");
        jLabel_TITULO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton_RAD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_RAD.setText("RAD");
        jButton_RAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_RADMouseClicked(evt);
            }
        });

        jLabel1.setText("Variables");

        jButton_varX.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_varX.setForeground(new java.awt.Color(204, 0, 0));
        jButton_varX.setText("X");
        jButton_varX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_varXMouseClicked(evt);
            }
        });

        jButton_varY.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_varY.setForeground(new java.awt.Color(204, 0, 0));
        jButton_varY.setText("Y");
        jButton_varY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_varYMouseClicked(evt);
            }
        });

        jButton_varZ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_varZ.setForeground(new java.awt.Color(204, 0, 0));
        jButton_varZ.setText("Z");
        jButton_varZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_varZMouseClicked(evt);
            }
        });

        jButton_DEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_DEL.setForeground(new java.awt.Color(255, 51, 51));
        jButton_DEL.setText("Borrar");
        jButton_DEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_DELMouseClicked(evt);
            }
        });

        jButton_0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_0.setText("0");
        jButton_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_0MouseClicked(evt);
            }
        });

        jButton_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_1.setText("1");
        jButton_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_1MouseClicked(evt);
            }
        });

        jButton_4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_4.setText("4");
        jButton_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_4MouseClicked(evt);
            }
        });

        jButton_7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_7.setText("7");
        jButton_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_7MouseClicked(evt);
            }
        });

        jButton_8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_8.setText("8");
        jButton_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_8MouseClicked(evt);
            }
        });

        jButton_5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_5.setText("5");
        jButton_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_5MouseClicked(evt);
            }
        });

        jButton_2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_2.setText("2");
        jButton_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_2MouseClicked(evt);
            }
        });

        jButton_PUNTO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_PUNTO.setText(".");
        jButton_PUNTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PUNTOMouseClicked(evt);
            }
        });

        jButton_IGUAL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_IGUAL.setText("ACEPTAR");
        jButton_IGUAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_IGUALMouseClicked(evt);
            }
        });

        jButton_3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_3.setText("3");
        jButton_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_3MouseClicked(evt);
            }
        });

        jButton_6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_6.setText("6");
        jButton_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_6MouseClicked(evt);
            }
        });

        jButton_9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_9.setText("9");
        jButton_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_9MouseClicked(evt);
            }
        });

        jButton_E.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_E.setText("E");
        jButton_E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_EMouseClicked(evt);
            }
        });

        jButton_PI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_PI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SAEAAV/Vista/Multimedia/PI_PNG.png"))); // NOI18N
        jButton_PI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PIMouseClicked(evt);
            }
        });

        jButton_POR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_POR.setText("X");
        jButton_POR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PORMouseClicked(evt);
            }
        });

        jButton_MAS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_MAS.setText("+");
        jButton_MAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_MASMouseClicked(evt);
            }
        });

        jButton_MENOS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_MENOS.setText("-");
        jButton_MENOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_MENOSMouseClicked(evt);
            }
        });

        jButton_ENTRE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ENTRE.setText("/");
        jButton_ENTRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ENTREMouseClicked(evt);
            }
        });

        jButton_AC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_AC.setForeground(new java.awt.Color(255, 51, 51));
        jButton_AC.setText("CLR");
        jButton_AC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ACMouseClicked(evt);
            }
        });

        jButton_TAN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_TAN.setText("TAN");
        jButton_TAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_TANMouseClicked(evt);
            }
        });

        jButton_PCIERRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_PCIERRA.setText(")");
        jButton_PCIERRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PCIERRAMouseClicked(evt);
            }
        });

        jButton_Borrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Borrar.setText("<-");
        jButton_Borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_BorrarMouseClicked(evt);
            }
        });

        jTextField_Display.setBackground(new java.awt.Color(153, 255, 204));
        jTextField_Display.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton_PABRE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_PABRE.setText("(");
        jButton_PABRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_PABREMouseClicked(evt);
            }
        });

        jButton_COS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_COS.setText("COS");
        jButton_COS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_COSMouseClicked(evt);
            }
        });

        jButton_SEN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_SEN.setText("SEN");
        jButton_SEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SENMouseClicked(evt);
            }
        });

        jButton_POT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_POT.setText("^");
        jButton_POT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_POTMouseClicked(evt);
            }
        });

        jButton_EXP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_EXP.setText("EXP");
        jButton_EXP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_EXPMouseClicked(evt);
            }
        });

        jButton_HYP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_HYP.setText("HYP");
        jButton_HYP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_HYPMouseClicked(evt);
            }
        });

        jButton_ARC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ARC.setText("ARC");
        jButton_ARC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ARCMouseClicked(evt);
            }
        });

        jButton_MOD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_MOD.setText("MOD");
        jButton_MOD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_MODMouseClicked(evt);
            }
        });

        jButton_DEG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_DEG.setText("DEG");
        jButton_DEG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_DEGMouseClicked(evt);
            }
        });

        jButton_SQRT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_SQRT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SAEAAV/Vista/Multimedia/SQRT_PNG.png"))); // NOI18N
        jButton_SQRT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SQRTMouseClicked(evt);
            }
        });

        jButton_LOG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_LOG.setText("LOG");
        jButton_LOG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_LOGMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_PCIERRA)
                    .addComponent(jButton_Borrar))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_LOG)
                            .addComponent(jButton_RAD)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_DEL, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_varX)
                                    .addComponent(jButton_varY)
                                    .addComponent(jButton_varZ))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_MOD)
                            .addComponent(jButton_7)
                            .addComponent(jButton_4)
                            .addComponent(jButton_1)
                            .addComponent(jButton_0)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton_SQRT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jButton_DEG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_EXP)
                            .addComponent(jButton_HYP)
                            .addComponent(jButton_ARC)
                            .addComponent(jButton_8)
                            .addComponent(jButton_5)
                            .addComponent(jButton_2)
                            .addComponent(jButton_PUNTO))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_IGUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_AC)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_3)
                                        .addComponent(jButton_SEN)
                                        .addComponent(jButton_POT)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButton_9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_E, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jButton_6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_COS)
                                        .addComponent(jButton_PABRE)
                                        .addComponent(jButton_MAS)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButton_PI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jButton_POR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(jButton_ENTRE))
                                        .addComponent(jButton_TAN)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(jButton_MENOS)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel_TITULO)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_TITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Borrar))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_SQRT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_LOG)
                        .addComponent(jButton_EXP)
                        .addComponent(jButton_PABRE)
                        .addComponent(jButton_PCIERRA)
                        .addComponent(jButton_POT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_SEN)
                    .addComponent(jButton_COS)
                    .addComponent(jButton_TAN)
                    .addComponent(jButton_HYP)
                    .addComponent(jButton_RAD)
                    .addComponent(jButton_DEG))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_PI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_ARC)
                        .addComponent(jButton_E)
                        .addComponent(jButton_MOD)
                        .addComponent(jLabel1))
                    .addComponent(jButton_AC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_POR)
                    .addComponent(jButton_ENTRE)
                    .addComponent(jButton_7)
                    .addComponent(jButton_8)
                    .addComponent(jButton_9)
                    .addComponent(jButton_varX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_MAS)
                    .addComponent(jButton_MENOS)
                    .addComponent(jButton_4)
                    .addComponent(jButton_5)
                    .addComponent(jButton_6)
                    .addComponent(jButton_varY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_1)
                    .addComponent(jButton_2)
                    .addComponent(jButton_3)
                    .addComponent(jButton_varZ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_0)
                    .addComponent(jButton_PUNTO)
                    .addComponent(jButton_IGUAL)
                    .addComponent(jButton_DEL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RADMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RADMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"RAD(");
    }//GEN-LAST:event_jButton_RADMouseClicked

    private void jButton_varXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_varXMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"X");
    }//GEN-LAST:event_jButton_varXMouseClicked

    private void jButton_varYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_varYMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"Y");
    }//GEN-LAST:event_jButton_varYMouseClicked

    private void jButton_varZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_varZMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"Z");
    }//GEN-LAST:event_jButton_varZMouseClicked

    private void jButton_DELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DELMouseClicked
        //System.exit(0);
        
        this.expresionDelUsuario="";
        this.jTextField_Display.setText("");
//        if(this.jTextField_campoTextoExpresion!=null)this.jTextField_campoTextoExpresion.setText(this.expresionDelUsuario);
//        if(this.jFrame_VentanaInvoca!=null)this.jFrame_VentanaInvoca.setEnabled(true);
//        //Le damos salida
//        setVisible(false); //you can't see me!
//        this.trabajando=false;
//        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_jButton_DELMouseClicked

    private void jButton_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_0MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"0");
    }//GEN-LAST:event_jButton_0MouseClicked

    private void jButton_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_1MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"1");
    }//GEN-LAST:event_jButton_1MouseClicked

    private void jButton_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_4MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"4");
    }//GEN-LAST:event_jButton_4MouseClicked

    private void jButton_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_7MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"7");
    }//GEN-LAST:event_jButton_7MouseClicked

    private void jButton_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_8MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"8");
    }//GEN-LAST:event_jButton_8MouseClicked

    private void jButton_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_5MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"5");
    }//GEN-LAST:event_jButton_5MouseClicked

    private void jButton_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_2MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"2");
    }//GEN-LAST:event_jButton_2MouseClicked

    private void jButton_PUNTOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PUNTOMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+".");
    }//GEN-LAST:event_jButton_PUNTOMouseClicked

    private void jButton_IGUALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_IGUALMouseClicked
        //AQUI RESUELVE
        //PROCESAMOS DIRECTO

        //Variables
        String contenido;

        //Leemos los datos del campo
        String textoDisplay=this.jTextField_Display.getText();

        //Los anclamos en el atributo que le corresponde
        this.expresionDelUsuario=textoDisplay;

        //Le damos salida
        if(this.jTextField_campoTextoExpresion!=null)
        {
            System.out.println("jTextField_campoTextoExpresion=NULL");
        }
        if(this.jTextField_campoTextoExpresion!=null)this.jTextField_campoTextoExpresion.setText(this.expresionDelUsuario);
        this.jButton_DELMouseClicked(null);
    }//GEN-LAST:event_jButton_IGUALMouseClicked

    private void jButton_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_3MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"3");
    }//GEN-LAST:event_jButton_3MouseClicked

    private void jButton_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_6MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"6");
    }//GEN-LAST:event_jButton_6MouseClicked

    private void jButton_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_9MouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"9");
    }//GEN-LAST:event_jButton_9MouseClicked

    private void jButton_EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"E");
    }//GEN-LAST:event_jButton_EMouseClicked

    private void jButton_PIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PIMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"PI");
    }//GEN-LAST:event_jButton_PIMouseClicked

    private void jButton_PORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PORMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"*");
    }//GEN-LAST:event_jButton_PORMouseClicked

    private void jButton_MASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_MASMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"+");
    }//GEN-LAST:event_jButton_MASMouseClicked

    private void jButton_MENOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_MENOSMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"-");
    }//GEN-LAST:event_jButton_MENOSMouseClicked

    private void jButton_ENTREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ENTREMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"/");
    }//GEN-LAST:event_jButton_ENTREMouseClicked

    private void jButton_ACMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ACMouseClicked
        this.jTextField_Display.setText("");
    }//GEN-LAST:event_jButton_ACMouseClicked

    private void jButton_TANMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_TANMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        int modo=0;
        if(this.modoTrigonometrica.equalsIgnoreCase("HYP"))
        {
            modo=1;
        }
        if(this.modoTrigonometrica.equalsIgnoreCase("ARC"))
        {
            modo=2;
        }
        if(this.modoTrigonometrica.equalsIgnoreCase("NORMAL"))
        {
            modo=3;
        }
        switch(modo)
        {
            case 1:
            this.jTextField_Display.setText(textoDisplay+"TANH(");
            break;
            case 2:
            this.jTextField_Display.setText(textoDisplay+"ARCTAN(");
            break;
            case 3:
            this.jTextField_Display.setText(textoDisplay+"TAN(");
            break;
        }
        this.modoTrigonometrica="NORMAL";
    }//GEN-LAST:event_jButton_TANMouseClicked

    private void jButton_PCIERRAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PCIERRAMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+")");
    }//GEN-LAST:event_jButton_PCIERRAMouseClicked

    private void jButton_BorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BorrarMouseClicked
        String textoDisplay=this.jTextField_Display.getText();

        if(textoDisplay.length()!=0)
        {
            textoDisplay=textoDisplay.substring(0, textoDisplay.length()-1);
        }

        this.jTextField_Display.setText(textoDisplay);
    }//GEN-LAST:event_jButton_BorrarMouseClicked

    private void jButton_PABREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_PABREMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"(");
    }//GEN-LAST:event_jButton_PABREMouseClicked

    private void jButton_COSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_COSMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        int modo=0;
        if(this.modoTrigonometrica.equalsIgnoreCase("HYP"))
        {
            modo=1;
        }
        if(this.modoTrigonometrica.equalsIgnoreCase("ARC"))
        {
            modo=2;
        }
        if(this.modoTrigonometrica.equalsIgnoreCase("NORMAL"))
        {
            modo=3;
        }
        switch(modo)
        {
            case 1:
            this.jTextField_Display.setText(textoDisplay+"COSH(");
            break;
            case 2:
            this.jTextField_Display.setText(textoDisplay+"ARCCOS(");
            break;
            case 3:
            this.jTextField_Display.setText(textoDisplay+"COS(");
            break;
        }
        this.modoTrigonometrica="NORMAL";
    }//GEN-LAST:event_jButton_COSMouseClicked

    private void jButton_SENMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SENMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        int modo=0;
        if(this.modoTrigonometrica.equalsIgnoreCase("HYP"))
        {
            modo=1;
        }
        if(this.modoTrigonometrica.equalsIgnoreCase("ARC"))
        {
            modo=2;
        }
        if(this.modoTrigonometrica.equalsIgnoreCase("NORMAL"))
        {
            modo=3;
        }
        switch(modo)
        {
            case 1:
            this.jTextField_Display.setText(textoDisplay+"SENH(");
            break;
            case 2:
            this.jTextField_Display.setText(textoDisplay+"ARCSEN(");
            break;
            case 3:
            this.jTextField_Display.setText(textoDisplay+"SEN(");
            break;
        }
        this.modoTrigonometrica="NORMAL";
    }//GEN-LAST:event_jButton_SENMouseClicked

    private void jButton_POTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_POTMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"^");
    }//GEN-LAST:event_jButton_POTMouseClicked

    private void jButton_EXPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EXPMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"EXP(");
    }//GEN-LAST:event_jButton_EXPMouseClicked

    private void jButton_HYPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_HYPMouseClicked
        this.modoTrigonometrica="HYP";
    }//GEN-LAST:event_jButton_HYPMouseClicked

    private void jButton_ARCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ARCMouseClicked
        this.modoTrigonometrica="ARC";
    }//GEN-LAST:event_jButton_ARCMouseClicked

    private void jButton_MODMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_MODMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"%");
    }//GEN-LAST:event_jButton_MODMouseClicked

    private void jButton_DEGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DEGMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"DEG(");
    }//GEN-LAST:event_jButton_DEGMouseClicked

    private void jButton_SQRTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SQRTMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"SQRT(");
    }//GEN-LAST:event_jButton_SQRTMouseClicked

    private void jButton_LOGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LOGMouseClicked
        String textoDisplay=this.jTextField_Display.getText();
        this.jTextField_Display.setText(textoDisplay+"LOG(");
    }//GEN-LAST:event_jButton_LOGMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JButton jButton_AC;
    private javax.swing.JButton jButton_ARC;
    private javax.swing.JButton jButton_Borrar;
    private javax.swing.JButton jButton_COS;
    private javax.swing.JButton jButton_DEG;
    private javax.swing.JButton jButton_DEL;
    private javax.swing.JButton jButton_E;
    private javax.swing.JButton jButton_ENTRE;
    private javax.swing.JButton jButton_EXP;
    private javax.swing.JButton jButton_HYP;
    private javax.swing.JButton jButton_IGUAL;
    private javax.swing.JButton jButton_LOG;
    private javax.swing.JButton jButton_MAS;
    private javax.swing.JButton jButton_MENOS;
    private javax.swing.JButton jButton_MOD;
    private javax.swing.JButton jButton_PABRE;
    private javax.swing.JButton jButton_PCIERRA;
    private javax.swing.JButton jButton_PI;
    private javax.swing.JButton jButton_POR;
    private javax.swing.JButton jButton_POT;
    private javax.swing.JButton jButton_PUNTO;
    private javax.swing.JButton jButton_RAD;
    private javax.swing.JButton jButton_SEN;
    private javax.swing.JButton jButton_SQRT;
    private javax.swing.JButton jButton_TAN;
    private javax.swing.JButton jButton_varX;
    private javax.swing.JButton jButton_varY;
    private javax.swing.JButton jButton_varZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_TITULO;
    private javax.swing.JTextField jTextField_Display;
    // End of variables declaration//GEN-END:variables

    public void setjTextField_campoTextoExpresion(javax.swing.JTextField jTextField_campoTextoExpresion) {
        this.jTextField_campoTextoExpresion = jTextField_campoTextoExpresion;
    }

    public String getExpresionDelUsuario() {
        return expresionDelUsuario;
    }
}
