/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.SAEAAV.Vista;

import com.SAEAAV.Modelo.Matematicas.Constantes_Matematicas;
import com.SAEAAV.Modelo.Principal_Modelo;

/**
 *
 * @author checo_checho
 */
public class UTL_JDialog_Visualizacion2D_OpcionesPlano extends javax.swing.JDialog {

    ///Atributos_Checo
    private Principal_Modelo objPrincipal_Modelo=null;
    private javax.swing.JFrame jFrame_VentanaInvoca=null;
    
    // Modo de Visualización
    private boolean esModo3D=false;
    private Integer plano=Constantes_Matematicas.PLANO_XY;
    
    /**
     * Creates new form UTL_JDialog_Visualizacion2D_OpcionesPlano
     */
    @Deprecated
    public UTL_JDialog_Visualizacion2D_OpcionesPlano(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public UTL_JDialog_Visualizacion2D_OpcionesPlano(java.awt.Frame parent, boolean modal, Principal_Modelo objPrincipal_Modelo) 
    {
        super(parent, modal);
        this.objPrincipal_Modelo=objPrincipal_Modelo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_PlanosVisualizacion = new javax.swing.ButtonGroup();
        jPanel_Principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_PlanoXY = new javax.swing.JRadioButton();
        jRadioButton_PlanoYZ = new javax.swing.JRadioButton();
        jRadioButton_PlanoXZ = new javax.swing.JRadioButton();
        jButton_Aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel_Principal.setBackground(java.awt.Color.white);

        jLabel1.setText("-Elija el Plano de Visualización-");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 30)); // NOI18N
        jLabel2.setText("Visualización 2D");

        buttonGroup_PlanosVisualizacion.add(jRadioButton_PlanoXY);
        jRadioButton_PlanoXY.setSelected(true);
        jRadioButton_PlanoXY.setText("Plano XY");
        jRadioButton_PlanoXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_PlanoXYActionPerformed(evt);
            }
        });

        buttonGroup_PlanosVisualizacion.add(jRadioButton_PlanoYZ);
        jRadioButton_PlanoYZ.setText("Plano YZ");
        jRadioButton_PlanoYZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_PlanoYZActionPerformed(evt);
            }
        });

        buttonGroup_PlanosVisualizacion.add(jRadioButton_PlanoXZ);
        jRadioButton_PlanoXZ.setText("Plano XZ");
        jRadioButton_PlanoXZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_PlanoXZActionPerformed(evt);
            }
        });

        jButton_Aceptar.setText("Aceptar");
        jButton_Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_PrincipalLayout = new javax.swing.GroupLayout(jPanel_Principal);
        jPanel_Principal.setLayout(jPanel_PrincipalLayout);
        jPanel_PrincipalLayout.setHorizontalGroup(
            jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                .addGroup(jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                                .addGroup(jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton_PlanoXZ)
                                    .addComponent(jRadioButton_PlanoXY)
                                    .addComponent(jRadioButton_PlanoYZ))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Aceptar))))
                    .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel_PrincipalLayout.setVerticalGroup(
            jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_PlanoXY)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_PlanoXZ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_PlanoYZ)
                    .addComponent(jButton_Aceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AceptarMouseClicked
        //Mandamos los datos al modelo
        if(this.objPrincipal_Modelo!=null)this.objPrincipal_Modelo.esModo2D(plano);
        
        //Cerramos la ventana y libearamos recursos
        this.dispose();
    }//GEN-LAST:event_jButton_AceptarMouseClicked

    private void jRadioButton_PlanoXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_PlanoXYActionPerformed
        //Ajustamos el Plano
        this.plano=Constantes_Matematicas.PLANO_XY;
    }//GEN-LAST:event_jRadioButton_PlanoXYActionPerformed

    private void jRadioButton_PlanoXZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_PlanoXZActionPerformed
        //Ajustamos el Plano
        this.plano=Constantes_Matematicas.PLANO_XZ;
    }//GEN-LAST:event_jRadioButton_PlanoXZActionPerformed

    private void jRadioButton_PlanoYZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_PlanoYZActionPerformed
        //Ajustamos el Plano
        this.plano=Constantes_Matematicas.PLANO_YZ;
    }//GEN-LAST:event_jRadioButton_PlanoYZActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UTL_JDialog_Visualizacion2D_OpcionesPlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UTL_JDialog_Visualizacion2D_OpcionesPlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UTL_JDialog_Visualizacion2D_OpcionesPlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UTL_JDialog_Visualizacion2D_OpcionesPlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                UTL_JDialog_Visualizacion2D_OpcionesPlano dialog = new UTL_JDialog_Visualizacion2D_OpcionesPlano(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_PlanosVisualizacion;
    private javax.swing.JButton jButton_Aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_Principal;
    private javax.swing.JRadioButton jRadioButton_PlanoXY;
    private javax.swing.JRadioButton jRadioButton_PlanoXZ;
    private javax.swing.JRadioButton jRadioButton_PlanoYZ;
    // End of variables declaration//GEN-END:variables
}
